export const mockVesselData = [
  {
    id: "v1",
    name: "DEF4 ILEX",
    type: "Chemical/Oil Products Tank",
    imo: "9876543",
    mmsi: "123456789",
    status: "clean",
    speed: 12.5,
    location: "BARCELONA (Spain)",
    position: { lat: 41.3851, lng: 2.1734 },
    deadweight: 50000,
    yearBuilt: 2022,
    vesselFlag: "Denmark",
    operator: "DEF4 CAPITAL PARTNERS APS",
    operatorNationality: "Denmark",
    lastCargoes: ["CPP", "ULSD", "GASOLINE"],
    laycanStart: "2024-05-10",
    laycanEnd: "2024-05-15",
    vesselName: "DEF4 ILEX",
    vesselType: "Chemical/Oil Products Tank",
    vesselSize: 50,
    loadPort: "BARCELONA",
    dischargePort: "ROTTERDAM",
    charterer: "DEF4 CAPITAL PARTNERS APS",
  },
  {
    id: "v2",
    name: "CLEAROCEAN MAVERICK",
    type: "Chemical/Oil Products Tank",
    imo: "9876544",
    mmsi: "123456790",
    status: "clean",
    speed: 11.8,
    location: "USG (United States)",
    position: { lat: 29.7604, lng: -95.3698 },
    deadweight: 50000,
    yearBuilt: 2021,
    vesselFlag: "Japan",
    operator: "FUKUHIN KISEN KK",
    operatorNationality: "Japan",
    lastCargoes: ["UMS/UMS/BIO-PALMS"],
    laycanStart: "2024-05-03",
    laycanEnd: "2024-05-08",
    vesselName: "CLEAROCEAN MAVERICK",
    vesselType: "Chemical/Oil Products Tank",
    vesselSize: 50,
    loadPort: "HOUSTON",
    dischargePort: "YOKOHAMA",
    charterer: "FUKUHIN KISEN KK",
  },
  {
    id: "v3",
    name: "GESI",
    type: "Crude Oil Tanker",
    imo: "9876545",
    mmsi: "123456791",
    status: "dirty",
    speed: 10.2,
    location: "SINGAPORE (Singapore St.)",
    position: { lat: 1.3521, lng: 103.8198 },
    deadweight: 305749,
    yearBuilt: 2007,
    vesselFlag: "Greece",
    operator: "ROUTE SHIPPING CO",
    operatorNationality: "Greece",
    lastCargoes: ["CRUDE", "CRUDE", "CRUDE"],
    laycanStart: "2024-04-30",
    laycanEnd: "2024-05-05",
    vesselName: "GESI",
    vesselType: "Crude Oil Tanker",
    vesselSize: 305,
    loadPort: "SINGAPORE",
    dischargePort: "PIRAEUS",
    charterer: "ROUTE SHIPPING CO",
  },
  {
    id: "v4",
    name: "NAVE CASSIOPEIA",
    type: "Crude Oil Tanker",
    imo: "9876546",
    mmsi: "123456792",
    status: "clean",
    speed: 13.1,
    location: "ARATU (Brazil)",
    position: { lat: -12.873, lng: -38.5108 },
    deadweight: 74711,
    yearBuilt: 2012,
    vesselFlag: "Greece",
    operator: "NAVIOS TANKERS MANAGEMENT INC",
    operatorNationality: "Greece",
    lastCargoes: ["NAP"],
    laycanStart: "2024-04-30",
    laycanEnd: "2024-05-05",
    vesselName: "NAVE CASSIOPEIA",
    vesselType: "Crude Oil Tanker",
    vesselSize: 74,
    loadPort: "ARATU",
    dischargePort: "PIRAEUS",
    charterer: "NAVIOS TANKERS MANAGEMENT INC",
  },
  {
    id: "v5",
    name: "NAVIOS WOLF",
    type: "Crude Oil Tanker",
    imo: "9876547",
    mmsi: "123456793",
    status: "clean",
    speed: 12.7,
    location: "TRAMANDAI (Brazil)",
    position: { lat: -30.0, lng: -50.13 },
    deadweight: 115394,
    yearBuilt: 2023,
    vesselFlag: "Germany",
    operator: "TB MARINE SHIPMANAGEMENT",
    operatorNationality: "Germany",
    lastCargoes: ["CLN COND"],
    laycanStart: "2024-05-08",
    laycanEnd: "2024-05-13",
    vesselName: "NAVIOS WOLF",
    vesselType: "Crude Oil Tanker",
    vesselSize: 115,
    loadPort: "TRAMANDAI",
    dischargePort: "HAMBURG",
    charterer: "TB MARINE SHIPMANAGEMENT",
  },
  {
    id: "v6",
    name: "NAVIOS MACALLISTER",
    type: "Oil Products Tanker",
    imo: "9876548",
    mmsi: "123456794",
    status: "clean",
    speed: 11.9,
    location: "SINGAPORE (Singapore St.)",
    position: { lat: 1.3521, lng: 103.8198 },
    deadweight: 75618,
    yearBuilt: 2012,
    vesselFlag: "Germany",
    operator: "ERNST JACOB GMBH & CO KG",
    operatorNationality: "Germany",
    lastCargoes: ["NAP"],
    laycanStart: "2024-05-08",
    laycanEnd: "2024-05-13",
    vesselName: "NAVIOS MACALLISTER",
    vesselType: "Oil Products Tanker",
    vesselSize: 75,
    loadPort: "SINGAPORE",
    dischargePort: "HAMBURG",
    charterer: "ERNST JACOB GMBH & CO KG",
  },
  {
    id: "v7",
    name: "NAVIOS MESSI",
    type: "Oil Products Tanker",
    imo: "9876549",
    mmsi: "123456795",
    status: "clean",
    speed: 12.3,
    location: "FUJAIRAH (United Arab Emi...)",
    position: { lat: 25.1919, lng: 56.3366 },
    deadweight: 75618,
    yearBuilt: 2011,
    vesselFlag: "Germany",
    operator: "TB MARINE SHIPMANAGEMENT",
    operatorNationality: "Germany",
    lastCargoes: ["NAP"],
    laycanStart: "2024-05-18",
    laycanEnd: "2024-05-23",
    vesselName: "NAVIOS MESSI",
    vesselType: "Oil Products Tanker",
    vesselSize: 75,
    loadPort: "FUJAIRAH",
    dischargePort: "HAMBURG",
    charterer: "TB MARINE SHIPMANAGEMENT",
  },
  {
    id: "v8",
    name: "NAVIOS MONTIEL",
    type: "Oil Products Tanker",
    imo: "9876550",
    mmsi: "123456796",
    status: "clean",
    speed: 11.5,
    location: "JEBEL ALI (United Arab Emi...)",
    position: { lat: 25.0481, lng: 55.0324 },
    deadweight: 75371,
    yearBuilt: 2012,
    vesselFlag: "Germany",
    operator: "TB MARINE SHIPMANAGEMENT",
    operatorNationality: "Germany",
    lastCargoes: ["JET"],
    laycanStart: "2024-05-08",
    laycanEnd: "2024-05-13",
    vesselName: "NAVIOS MONTIEL",
    vesselType: "Oil Products Tanker",
    vesselSize: 75,
    loadPort: "JEBEL ALI",
    dischargePort: "HAMBURG",
    charterer: "TB MARINE SHIPMANAGEMENT",
  },
  {
    id: "v9",
    name: "NAVIOS PASSION",
    type: "Crude Oil Tanker",
    imo: "9876551",
    mmsi: "123456797",
    status: "clean",
    speed: 12.8,
    location: "CHIBA (Japan)",
    position: { lat: 35.6074, lng: 140.1065 },
    deadweight: 109992,
    yearBuilt: 2019,
    vesselFlag: "Singapore",
    operator: "NAVIOS GROUP",
    operatorNationality: "Singapore Sta",
    lastCargoes: ["NAP"],
    laycanStart: "2024-05-14",
    laycanEnd: "2024-05-19",
    vesselName: "NAVIOS PASSION",
    vesselType: "Crude Oil Tanker",
    vesselSize: 109,
    loadPort: "CHIBA",
    dischargePort: "SINGAPORE",
    charterer: "NAVIOS GROUP",
  },
  {
    id: "v10",
    name: "LADY HENRIETTA",
    type: "Crude Oil Tanker",
    imo: "9876552",
    mmsi: "123456798",
    status: "clean",
    speed: 11.7,
    location: "Dalian (China)",
    position: { lat: 38.914, lng: 121.6147 },
    deadweight: 112072,
    yearBuilt: 2012,
    vesselFlag: "Greece",
    operator: "LATSCO MARINE MANAGEMENT INC",
    operatorNationality: "Greece",
    lastCargoes: ["NAP"],
    laycanStart: "2024-05-03",
    laycanEnd: "2024-05-08",
    vesselName: "LADY HENRIETTA",
    vesselType: "Crude Oil Tanker",
    vesselSize: 112,
    loadPort: "DALIAN",
    dischargePort: "PIRAEUS",
    charterer: "LATSCO MARINE MANAGEMENT INC",
  },
]
